name: learn-github-actions

on:
  push:
    branches:
      - master

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install bats
        run: npm install -g bats
      - name: Check bats version
        run: bats -v
      - name: Use Secret
        env:
          FIRST_KEY: ${{secrets.FIRST_KEY}}
        run: |
          echo "Writing to the file"
          echo "Key : $FIRST_KEY" -> my-file.txt
          cat my-file.txt
      - name: "Display File Contens"
        run: |
          echo "Contents  of my-file.txt"
          cat my-file.txt



