name: learn-github-actions

on:
  push:
    branches:
      - master

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and Write to File
        env:
          ENV_VALUE: ${{ secrets.ENV_VALUE }}
        run: |
          echo "Writing value to file..."
          echo "Key: $ENV_VALUE" > my-file.txt

      - name: Display File Contents
        id: display-contents
        run: |
          echo "Contents of my-file.txt:"
          cat my-file.txt

      - name: Use File Contents
        run: |
          echo "File Contents: ${{ steps.display-contents.outputs.file-contents }}"
