name: learn-github-actions

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install bats
        run: npm install -g bats
      - name: Check bats version
        run: bats -v
      - name: Use Secret
        env:
          FIRST_KEY: ${{ secrets.FIRST_KEY }}
        run: |
          echo "The secret key value is $FIRST_KEY"
